### ISSUE TITLE
efivar fails to build with 4.8.x

### ISSUE THREAD

**Issue by WenzongFan** [rhboot/efivar#87]
For example:
On Ubuntu 14.04.4 LTS \n \l

$ gcc --version
gcc (Ubuntu 4.8.4-2ubuntu1~14.04.3) 4.8.4
Copyright (C) 2013 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

| dp.c: In function ‘efidp_duplicate_extra’:
| dp.c:78:2: warning: implicit declaration of function ‘_Generic’ [-Wimplicit-function-declaration]
|   if (add(sz, extra, &plus)) {
|   ^
| In file included from dp.c:27:0:
| util.h:109:10: error: expected expression before ‘int’
|           int *: int_add(a,b,c),   \
|           ^
| dp.c:78:6: note: in expansion of macro ‘add’
|   if (add(sz, extra, &plus)) {
|       ^
| dp.c:65:58: warning: unused parameter ‘extra’ [-Wunused-parameter]
|  efidp_duplicate_extra(const_efidp dp, efidp *out, size_t extra)
|                                                           ^

**Comment by vathpela** [comment]
Pretty sure this should be fixed now; if it's not, please do re-open it.
